[profile.default]
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
test = 'test-foundry'
cache_path  = 'forge-cache'
optimizer = true
optimizer_runs = 100
via_ir = false
fs_permissions = [{ access = "read", path = "node_modules/@offchainlabs/stablecoin-evm"}]

[fmt]
number_underscore = 'thousands'
line_length = 100
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[lint]
lint_on_build = false